# Generated by Django 3.2.6 on 2021-10-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Water', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='water',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
